#!/bin/bash

# Autocomplete is not implemented yet. Will be implemented in the future. Probably 🤷‍♂️

# declare colors
red='\033[0;31m'
default='\033[0m'

# declare arguments as variables to make it clear
provider=$1
action=$2

# declare lib path
lib_path=/lib/scripts

# validate command
if [ -z "${provider}" ] || [ -z "${action}" ]
then
  printf "${red}Error: Invalid command.${default}\\n"
  printf "\\n"
  printf "Valid command:\\n"
  printf "scripts <provider> <action>\\n"

  exit 2
fi

# validate first argument
folder_exists=$(find $lib_path -type d -name "$provider")
if [ -z "${folder_exists}" ]
then
  printf "${red}Error: Unknown argument $provider.${default}\\n"
  printf "\\n"
  printf "First argument should one of these options:\\n"
  printf "clickup gitlab life ms-teams\\n"

  exit 2
fi

# validate second argument
file_exists=$(find $lib_path -name "$action.sh")
if [ -z "${file_exists}" ]
then
  printf "${red}Error: Unknown argument $action.${default}\\n"

  exit 2
fi

# execute file
bash -i $lib_path/$provider/$action.sh $@

exit 0